os:
  - linux   # https://docs.travis-ci.com/user/reference/linux/
  # - osx
  # - windows

dist: focal   # Ubuntu 20.04, gcc 9.3.0
sudo: require
language: cpp

script:
  - bash bin/clean  
  - bash bin/ci_scan-build
  # - bash bin/ci_cppcheck
  # - bash bin/ci 
  # - bash bin/run-unit-tests 

# end of file
